# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crosschaintransfer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63rosschaintransfer.proto\"\xa6\x01\n\x12\x43rossChainTransfer\x12\x0f\n\x07tokenID\x18\x01 \x02(\x0c\x12\x0e\n\x06\x61mount\x18\x02 \x02(\x04\x12\x18\n\x10receivingChainID\x18\x03 \x02(\x0c\x12\x18\n\x10recipientAddress\x18\x04 \x02(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x05 \x02(\t\x12\x12\n\nmessageFee\x18\x06 \x02(\x04\x12\x19\n\x11messageFeeTokenID\x18\x07 \x02(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crosschaintransfer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CROSSCHAINTRANSFER._serialized_start=29
  _CROSSCHAINTRANSFER._serialized_end=195
# @@protoc_insertion_point(module_scope)
