# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crosschainupdate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63rosschainupdate.proto\"\xdb\x01\n\x10\x43rossChainUpdate\x12\x16\n\x0esendingChainID\x18\x01 \x02(\x0c\x12\x13\n\x0b\x63\x65rtificate\x18\x02 \x02(\x0c\x12H\n\x16\x61\x63tiveValidatorsUpdate\x18\x03 \x02(\x0b\x32(.CrossChainUpdate_ActiveValidatorsUpdate\x12\x1c\n\x14\x63\x65rtificateThreshold\x18\x04 \x02(\x04\x12\x32\n\x0binboxUpdate\x18\x05 \x02(\x0b\x32\x1d.CrossChainUpdate_InboxUpdate\"\x98\x01\n\x1c\x43rossChainUpdate_InboxUpdate\x12\x1a\n\x12\x63rossChainMessages\x18\x01 \x03(\x0c\x12\x1c\n\x14messageWitnessHashes\x18\x02 \x03(\x0c\x12>\n\x11outboxRootWitness\x18\x03 \x02(\x0b\x32#.CrossChainUpdate_OutboxRootWitness\"K\n\"CrossChainUpdate_OutboxRootWitness\x12\x0e\n\x06\x62itmap\x18\x01 \x02(\x0c\x12\x15\n\rsiblingHashes\x18\x02 \x03(\x0c\"~\n\'CrossChainUpdate_ActiveValidatorsUpdate\x12\x15\n\rblsKeysUpdate\x18\x01 \x03(\x0c\x12\x1c\n\x10\x62\x66tWeightsUpdate\x18\x02 \x03(\x04\x42\x02\x10\x01\x12\x1e\n\x16\x62\x66tWeightsUpdateBitmap\x18\x03 \x02(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crosschainupdate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CROSSCHAINUPDATE_ACTIVEVALIDATORSUPDATE.fields_by_name['bftWeightsUpdate']._options = None
  _CROSSCHAINUPDATE_ACTIVEVALIDATORSUPDATE.fields_by_name['bftWeightsUpdate']._serialized_options = b'\020\001'
  _CROSSCHAINUPDATE._serialized_start=27
  _CROSSCHAINUPDATE._serialized_end=246
  _CROSSCHAINUPDATE_INBOXUPDATE._serialized_start=249
  _CROSSCHAINUPDATE_INBOXUPDATE._serialized_end=401
  _CROSSCHAINUPDATE_OUTBOXROOTWITNESS._serialized_start=403
  _CROSSCHAINUPDATE_OUTBOXROOTWITNESS._serialized_end=478
  _CROSSCHAINUPDATE_ACTIVEVALIDATORSUPDATE._serialized_start=480
  _CROSSCHAINUPDATE_ACTIVEVALIDATORSUPDATE._serialized_end=606
# @@protoc_insertion_point(module_scope)
