# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainchainregistrationparams.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!mainchainregistrationparams.proto\"\xe4\x01\n\x1bMainchainRegistrationParams\x12\x12\n\nownChainID\x18\x01 \x02(\x0c\x12\x0f\n\x07ownName\x18\x02 \x02(\t\x12M\n\x13mainchainValidators\x18\x03 \x03(\x0b\x32\x30.MainchainRegistrationParams_MainchainValidators\x12%\n\x1dmainchainCertificateThreshold\x18\x04 \x02(\x04\x12\x11\n\tsignature\x18\x05 \x02(\x0c\x12\x17\n\x0f\x61ggregationBits\x18\x06 \x02(\x0c\"T\n/MainchainRegistrationParams_MainchainValidators\x12\x0e\n\x06\x62lsKey\x18\x01 \x02(\x0c\x12\x11\n\tbftWeight\x18\x02 \x02(\x04')



_MAINCHAINREGISTRATIONPARAMS = DESCRIPTOR.message_types_by_name['MainchainRegistrationParams']
_MAINCHAINREGISTRATIONPARAMS_MAINCHAINVALIDATORS = DESCRIPTOR.message_types_by_name['MainchainRegistrationParams_MainchainValidators']
MainchainRegistrationParams = _reflection.GeneratedProtocolMessageType('MainchainRegistrationParams', (_message.Message,), {
  'DESCRIPTOR' : _MAINCHAINREGISTRATIONPARAMS,
  '__module__' : 'mainchainregistrationparams_pb2'
  # @@protoc_insertion_point(class_scope:MainchainRegistrationParams)
  })
_sym_db.RegisterMessage(MainchainRegistrationParams)

MainchainRegistrationParams_MainchainValidators = _reflection.GeneratedProtocolMessageType('MainchainRegistrationParams_MainchainValidators', (_message.Message,), {
  'DESCRIPTOR' : _MAINCHAINREGISTRATIONPARAMS_MAINCHAINVALIDATORS,
  '__module__' : 'mainchainregistrationparams_pb2'
  # @@protoc_insertion_point(class_scope:MainchainRegistrationParams_MainchainValidators)
  })
_sym_db.RegisterMessage(MainchainRegistrationParams_MainchainValidators)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAINCHAINREGISTRATIONPARAMS._serialized_start=38
  _MAINCHAINREGISTRATIONPARAMS._serialized_end=266
  _MAINCHAINREGISTRATIONPARAMS_MAINCHAINVALIDATORS._serialized_start=268
  _MAINCHAINREGISTRATIONPARAMS_MAINCHAINVALIDATORS._serialized_end=352
# @@protoc_insertion_point(module_scope)
