# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registersidechain.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17registersidechain.proto\"\x9e\x01\n\x11RegisterSidechain\x12\x0f\n\x07\x63hainID\x18\x01 \x02(\x0c\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x43\n\x13sidechainValidators\x18\x03 \x03(\x0b\x32&.RegisterSidechain_SidechainValidators\x12%\n\x1dsidechainCertificateThreshold\x18\x04 \x02(\x04\"J\n%RegisterSidechain_SidechainValidators\x12\x0e\n\x06\x62lsKey\x18\x01 \x02(\x0c\x12\x11\n\tbftWeight\x18\x02 \x02(\x04')



_REGISTERSIDECHAIN = DESCRIPTOR.message_types_by_name['RegisterSidechain']
_REGISTERSIDECHAIN_SIDECHAINVALIDATORS = DESCRIPTOR.message_types_by_name['RegisterSidechain_SidechainValidators']
RegisterSidechain = _reflection.GeneratedProtocolMessageType('RegisterSidechain', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERSIDECHAIN,
  '__module__' : 'registersidechain_pb2'
  # @@protoc_insertion_point(class_scope:RegisterSidechain)
  })
_sym_db.RegisterMessage(RegisterSidechain)

RegisterSidechain_SidechainValidators = _reflection.GeneratedProtocolMessageType('RegisterSidechain_SidechainValidators', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERSIDECHAIN_SIDECHAINVALIDATORS,
  '__module__' : 'registersidechain_pb2'
  # @@protoc_insertion_point(class_scope:RegisterSidechain_SidechainValidators)
  })
_sym_db.RegisterMessage(RegisterSidechain_SidechainValidators)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERSIDECHAIN._serialized_start=28
  _REGISTERSIDECHAIN._serialized_end=186
  _REGISTERSIDECHAIN_SIDECHAINVALIDATORS._serialized_start=188
  _REGISTERSIDECHAIN_SIDECHAINVALIDATORS._serialized_end=262
# @@protoc_insertion_point(module_scope)
