# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reclaimlsk.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10reclaimlsk.proto\"\x1c\n\nReclaimLSK\x12\x0e\n\x06\x61mount\x18\x01 \x02(\x04')



_RECLAIMLSK = DESCRIPTOR.message_types_by_name['ReclaimLSK']
ReclaimLSK = _reflection.GeneratedProtocolMessageType('ReclaimLSK', (_message.Message,), {
  'DESCRIPTOR' : _RECLAIMLSK,
  '__module__' : 'reclaimlsk_pb2'
  # @@protoc_insertion_point(class_scope:ReclaimLSK)
  })
_sym_db.RegisterMessage(ReclaimLSK)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECLAIMLSK._serialized_start=20
  _RECLAIMLSK._serialized_end=48
# @@protoc_insertion_point(module_scope)
