# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unlocktest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10unlocktest.proto\"\x0c\n\nUnlockTest')



_UNLOCKTEST = DESCRIPTOR.message_types_by_name['UnlockTest']
UnlockTest = _reflection.GeneratedProtocolMessageType('UnlockTest', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKTEST,
  '__module__' : 'unlocktest_pb2'
  # @@protoc_insertion_point(class_scope:UnlockTest)
  })
_sym_db.RegisterMessage(UnlockTest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNLOCKTEST._serialized_start=20
  _UNLOCKTEST._serialized_end=32
# @@protoc_insertion_point(module_scope)
