LSK = 10**8
PUB_KEY_LENGTH = 32
ADDRESS_LENGTH = 20
SEED_LENGTH = 32

DEFAULT_LISK32_ADDRESS_PREFIX = "lsk"
LISK32_ADDRESS_LENGTH = 41
LISK32_CHARSET = "zxvcpmbn3465o978uyrtkqew2adsjhfg"

EDSA_SIGNATURE_LENGTH = 64
EDSA_PUBLIC_KEY_LENGTH = 32

EVENT_TAGS = [
    "user_input",
    "service_subscription",
    "api_response"
]

BALANCE_TRANSFER_LENGTH = 150
BALANCE_TRANSFER_MAX_DATA_LENGTH = 64