# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openswap.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eopenswap.proto\"s\n\x08OpenSwap\x12\x0e\n\x06swapID\x18\x01 \x02(\x0c\x12\x0f\n\x07tokenID\x18\x02 \x02(\x0c\x12\r\n\x05value\x18\x03 \x02(\x04\x12\x18\n\x10recipientAddress\x18\x04 \x02(\x0c\x12\x10\n\x08timelock\x18\x05 \x02(\r\x12\x0b\n\x03tip\x18\x06 \x02(\x04')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openswap_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPENSWAP._serialized_start=18
  _OPENSWAP._serialized_end=133
# @@protoc_insertion_point(module_scope)
