# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dingus/codec/asset.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64ingus/codec/asset.proto\"\'\n\x05\x41sset\x12\x10\n\x08moduleID\x18\x01 \x02(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c')



_ASSET = DESCRIPTOR.message_types_by_name['Asset']
Asset = _reflection.GeneratedProtocolMessageType('Asset', (_message.Message,), {
  'DESCRIPTOR' : _ASSET,
  '__module__' : 'dingus.codec.asset_pb2'
  # @@protoc_insertion_point(class_scope:Asset)
  })
_sym_db.RegisterMessage(Asset)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ASSET._serialized_start=28
  _ASSET._serialized_end=67
# @@protoc_insertion_point(module_scope)
