# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dingus/codec/block.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64ingus/codec/block.proto\"F\n\x05\x42lock\x12\x17\n\x06header\x18\x01 \x02(\x0b\x32\x07.Header\x12\x14\n\x0ctransactions\x18\x02 \x03(\x0c\x12\x0e\n\x06\x61ssets\x18\x03 \x03(\x0c\"\xaf\x03\n\x06Header\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x11\n\ttimestamp\x18\x02 \x02(\r\x12\x0e\n\x06height\x18\x03 \x02(\r\x12\x17\n\x0fpreviousBlockID\x18\x04 \x02(\x0c\x12\x18\n\x10generatorAddress\x18\x05 \x02(\x0c\x12\x17\n\x0ftransactionRoot\x18\x06 \x02(\x0c\x12\x11\n\tassetRoot\x18\x07 \x02(\x0c\x12\x11\n\teventRoot\x18\x08 \x02(\x0c\x12\x11\n\tstateRoot\x18\t \x02(\x0c\x12\x19\n\x11maxHeightPrevoted\x18\n \x02(\r\x12\x1a\n\x12maxHeightGenerated\x18\x0b \x02(\r\x12\x16\n\x0evalidatorsHash\x18\x0c \x02(\x0c\x12\x30\n\x0f\x61ggregateCommit\x18\r \x02(\x0b\x32\x17.Header.AggregateCommit\x12\x11\n\tsignature\x18\x0e \x01(\x0c\x1aX\n\x0f\x41ggregateCommit\x12\x0e\n\x06height\x18\x01 \x02(\r\x12\x17\n\x0f\x61ggregationBits\x18\x02 \x02(\x0c\x12\x1c\n\x14\x63\x65rtificateSignature\x18\x03 \x02(\x0c')



_BLOCK = DESCRIPTOR.message_types_by_name['Block']
_HEADER = DESCRIPTOR.message_types_by_name['Header']
_HEADER_AGGREGATECOMMIT = _HEADER.nested_types_by_name['AggregateCommit']
Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'dingus.codec.block_pb2'
  # @@protoc_insertion_point(class_scope:Block)
  })
_sym_db.RegisterMessage(Block)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {

  'AggregateCommit' : _reflection.GeneratedProtocolMessageType('AggregateCommit', (_message.Message,), {
    'DESCRIPTOR' : _HEADER_AGGREGATECOMMIT,
    '__module__' : 'dingus.codec.block_pb2'
    # @@protoc_insertion_point(class_scope:Header.AggregateCommit)
    })
  ,
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'dingus.codec.block_pb2'
  # @@protoc_insertion_point(class_scope:Header)
  })
_sym_db.RegisterMessage(Header)
_sym_db.RegisterMessage(Header.AggregateCommit)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLOCK._serialized_start=28
  _BLOCK._serialized_end=98
  _HEADER._serialized_start=101
  _HEADER._serialized_end=532
  _HEADER_AGGREGATECOMMIT._serialized_start=444
  _HEADER_AGGREGATECOMMIT._serialized_end=532
# @@protoc_insertion_point(module_scope)
