# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62lock.proto\"=\n\x05\x42lock\x12\x0e\n\x06header\x18\x01 \x02(\x0c\x12\x14\n\x0ctransactions\x18\x02 \x03(\x0c\x12\x0e\n\x06\x61ssets\x18\x03 \x03(\x0c\"%\n\x05\x41sset\x12\x0e\n\x06module\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\"X\n\x0f\x41ggregateCommit\x12\x0e\n\x06height\x18\x01 \x02(\r\x12\x17\n\x0f\x61ggregationBits\x18\x02 \x02(\x0c\x12\x1c\n\x14\x63\x65rtificateSignature\x18\x03 \x02(\x0c\"\xea\x02\n\x06Header\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x11\n\ttimestamp\x18\x02 \x02(\r\x12\x0e\n\x06height\x18\x03 \x02(\r\x12\x17\n\x0fpreviousBlockID\x18\x04 \x02(\x0c\x12\x18\n\x10generatorAddress\x18\x05 \x02(\x0c\x12\x17\n\x0ftransactionRoot\x18\x06 \x02(\x0c\x12\x11\n\tassetRoot\x18\x07 \x02(\x0c\x12\x11\n\teventRoot\x18\x08 \x02(\x0c\x12\x11\n\tstateRoot\x18\t \x02(\x0c\x12\x19\n\x11maxHeightPrevoted\x18\n \x02(\r\x12\x1a\n\x12maxHeightGenerated\x18\x0b \x02(\r\x12\x1a\n\x12impliesMaxPrevotes\x18\x0c \x02(\x08\x12\x16\n\x0evalidatorsHash\x18\r \x02(\x0c\x12)\n\x0f\x61ggregateCommit\x18\x0e \x02(\x0b\x32\x10.AggregateCommit\x12\x11\n\tsignature\x18\x0f \x01(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'block_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLOCK._serialized_start=15
  _BLOCK._serialized_end=76
  _ASSET._serialized_start=78
  _ASSET._serialized_end=115
  _AGGREGATECOMMIT._serialized_start=117
  _AGGREGATECOMMIT._serialized_end=205
  _HEADER._serialized_start=208
  _HEADER._serialized_end=570
# @@protoc_insertion_point(module_scope)
