# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: certificate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x65rtificate.proto\"\x98\x01\n\x0b\x43\x65rtificate\x12\x0f\n\x07\x62lockID\x18\x01 \x02(\x0c\x12\x0e\n\x06height\x18\x02 \x02(\r\x12\x11\n\ttimestamp\x18\x03 \x02(\r\x12\x11\n\tstateRoot\x18\x04 \x02(\x0c\x12\x16\n\x0evalidatorsHash\x18\x05 \x02(\x0c\x12\x17\n\x0f\x61ggregationBits\x18\x06 \x01(\x0c\x12\x11\n\tsignature\x18\x07 \x01(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'certificate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CERTIFICATE._serialized_start=22
  _CERTIFICATE._serialized_end=174
# @@protoc_insertion_point(module_scope)
