# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainchainregistrationmessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"mainchainregistrationmessage.proto\"\xba\x01\n\x1cMainchainRegistrationMessage\x12\x12\n\nownChainID\x18\x01 \x02(\x0c\x12\x0f\n\x07ownName\x18\x02 \x02(\t\x12N\n\x13mainchainValidators\x18\x03 \x03(\x0b\x32\x31.MainchainRegistrationMessage_MainchainValidators\x12%\n\x1dmainchainCertificateThreshold\x18\x04 \x02(\x04\"U\n0MainchainRegistrationMessage_MainchainValidators\x12\x0e\n\x06\x62lsKey\x18\x01 \x02(\x0c\x12\x11\n\tbftWeight\x18\x02 \x02(\x04')



_MAINCHAINREGISTRATIONMESSAGE = DESCRIPTOR.message_types_by_name['MainchainRegistrationMessage']
_MAINCHAINREGISTRATIONMESSAGE_MAINCHAINVALIDATORS = DESCRIPTOR.message_types_by_name['MainchainRegistrationMessage_MainchainValidators']
MainchainRegistrationMessage = _reflection.GeneratedProtocolMessageType('MainchainRegistrationMessage', (_message.Message,), {
  'DESCRIPTOR' : _MAINCHAINREGISTRATIONMESSAGE,
  '__module__' : 'mainchainregistrationmessage_pb2'
  # @@protoc_insertion_point(class_scope:MainchainRegistrationMessage)
  })
_sym_db.RegisterMessage(MainchainRegistrationMessage)

MainchainRegistrationMessage_MainchainValidators = _reflection.GeneratedProtocolMessageType('MainchainRegistrationMessage_MainchainValidators', (_message.Message,), {
  'DESCRIPTOR' : _MAINCHAINREGISTRATIONMESSAGE_MAINCHAINVALIDATORS,
  '__module__' : 'mainchainregistrationmessage_pb2'
  # @@protoc_insertion_point(class_scope:MainchainRegistrationMessage_MainchainValidators)
  })
_sym_db.RegisterMessage(MainchainRegistrationMessage_MainchainValidators)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAINCHAINREGISTRATIONMESSAGE._serialized_start=39
  _MAINCHAINREGISTRATIONMESSAGE._serialized_end=225
  _MAINCHAINREGISTRATIONMESSAGE_MAINCHAINVALIDATORS._serialized_start=227
  _MAINCHAINREGISTRATIONMESSAGE_MAINCHAINVALIDATORS._serialized_end=312
# @@protoc_insertion_point(module_scope)
