# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dingus/codec/token_balance_transfer_params.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0dingus/codec/token_balance_transfer_params.proto\"\x82\x01\n\x15\x42\x61lanceTransferParams\x12\x0f\n\x07tokenID\x18\x01 \x02(\x0c\x12\x0e\n\x06\x61mount\x18\x02 \x02(\x04\x12\x18\n\x10recipientAddress\x18\x03 \x02(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x04 \x02(\t\x12 \n\x18\x61\x63\x63ountInitializationFee\x18\x05 \x02(\x04')



_BALANCETRANSFERPARAMS = DESCRIPTOR.message_types_by_name['BalanceTransferParams']
BalanceTransferParams = _reflection.GeneratedProtocolMessageType('BalanceTransferParams', (_message.Message,), {
  'DESCRIPTOR' : _BALANCETRANSFERPARAMS,
  '__module__' : 'dingus.codec.token_balance_transfer_params_pb2'
  # @@protoc_insertion_point(class_scope:BalanceTransferParams)
  })
_sym_db.RegisterMessage(BalanceTransferParams)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BALANCETRANSFERPARAMS._serialized_start=53
  _BALANCETRANSFERPARAMS._serialized_end=183
# @@protoc_insertion_point(module_scope)
