# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token_balance_transfer_asset.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="token_balance_transfer_asset.proto",
    package="",
    syntax="proto2",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n"token_balance_transfer_asset.proto"N\n\x14\x42\x61lanceTransferAsset\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x04\x12\x18\n\x10recipientAddress\x18\x02 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t',
)


_BALANCETRANSFERASSET = _descriptor.Descriptor(
    name="BalanceTransferAsset",
    full_name="BalanceTransferAsset",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="amount",
            full_name="BalanceTransferAsset.amount",
            index=0,
            number=1,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="recipientAddress",
            full_name="BalanceTransferAsset.recipientAddress",
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="data",
            full_name="BalanceTransferAsset.data",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=38,
    serialized_end=116,
)

DESCRIPTOR.message_types_by_name["BalanceTransferAsset"] = _BALANCETRANSFERASSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BalanceTransferAsset = _reflection.GeneratedProtocolMessageType(
    "BalanceTransferAsset",
    (_message.Message,),
    {
        "DESCRIPTOR": _BALANCETRANSFERASSET,
        "__module__": "token_balance_transfer_asset_pb2"
        # @@protoc_insertion_point(class_scope:BalanceTransferAsset)
    },
)
_sym_db.RegisterMessage(BalanceTransferAsset)


# @@protoc_insertion_point(module_scope)
