# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dingus/codec/token_balance_transfer_asset.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/dingus/codec/token_balance_transfer_asset.proto\"N\n\x14\x42\x61lanceTransferAsset\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x04\x12\x18\n\x10recipientAddress\x18\x02 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t')



_BALANCETRANSFERASSET = DESCRIPTOR.message_types_by_name['BalanceTransferAsset']
BalanceTransferAsset = _reflection.GeneratedProtocolMessageType('BalanceTransferAsset', (_message.Message,), {
  'DESCRIPTOR' : _BALANCETRANSFERASSET,
  '__module__' : 'dingus.codec.token_balance_transfer_asset_pb2'
  # @@protoc_insertion_point(class_scope:BalanceTransferAsset)
  })
_sym_db.RegisterMessage(BalanceTransferAsset)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BALANCETRANSFERASSET._serialized_start=51
  _BALANCETRANSFERASSET._serialized_end=129
# @@protoc_insertion_point(module_scope)
