# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validators.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10validators.proto\".\n\tValidator\x12\x0e\n\x06\x62lsKey\x18\x01 \x02(\x0c\x12\x11\n\tbftWeight\x18\x02 \x02(\x04\"J\n\nValidators\x12\x1e\n\nvalidators\x18\x01 \x03(\x0b\x32\n.Validator\x12\x1c\n\x14\x63\x65rtificateThreshold\x18\x02 \x02(\x04')



_VALIDATOR = DESCRIPTOR.message_types_by_name['Validator']
_VALIDATORS = DESCRIPTOR.message_types_by_name['Validators']
Validator = _reflection.GeneratedProtocolMessageType('Validator', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATOR,
  '__module__' : 'validators_pb2'
  # @@protoc_insertion_point(class_scope:Validator)
  })
_sym_db.RegisterMessage(Validator)

Validators = _reflection.GeneratedProtocolMessageType('Validators', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATORS,
  '__module__' : 'validators_pb2'
  # @@protoc_insertion_point(class_scope:Validators)
  })
_sym_db.RegisterMessage(Validators)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALIDATOR._serialized_start=20
  _VALIDATOR._serialized_end=66
  _VALIDATORS._serialized_start=68
  _VALIDATORS._serialized_end=142
# @@protoc_insertion_point(module_scope)
