# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registervalidator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17registervalidator.proto\"b\n\x11RegisterValidator\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06\x62lsKey\x18\x02 \x02(\x0c\x12\x19\n\x11proofOfPossession\x18\x03 \x02(\x0c\x12\x14\n\x0cgeneratorKey\x18\x04 \x02(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registervalidator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERVALIDATOR._serialized_start=27
  _REGISTERVALIDATOR._serialized_end=125
# @@protoc_insertion_point(module_scope)
