# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stake.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstake.proto\"&\n\x05Stake\x12\x1d\n\x06stakes\x18\x01 \x03(\x0b\x32\r.Stake_Stakes\"8\n\x0cStake_Stakes\x12\x18\n\x10validatorAddress\x18\x01 \x02(\x0c\x12\x0e\n\x06\x61mount\x18\x02 \x02(\x12')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stake_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STAKE._serialized_start=15
  _STAKE._serialized_end=53
  _STAKE_STAKES._serialized_start=55
  _STAKE_STAKES._serialized_end=111
# @@protoc_insertion_point(module_scope)
